# -*- coding: utf-8 -*-
"""
Genera fonts_data.py en la misma carpeta que este script (y que app.py).
Uso en PowerShell, dentro de "EduTrack Sistema academico":

  python crear_fonts_data.py

Si no hay fuentes locales, las descarga de GitHub (necesitas internet).
"""
from __future__ import print_function
import os
import sys
import base64
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "fonts_data.py")

CANDIDATES = [
    (os.path.join(HERE, "static", "fonts", "DejaVuSans.ttf"),
     os.path.join(HERE, "static", "fonts", "DejaVuSans-Bold.ttf")),
    (os.path.join(HERE, "DejaVuSans.ttf"),
     os.path.join(HERE, "DejaVuSans-Bold.ttf")),
]


def download_fonts(dest_dir):
    try:
        from urllib.request import urlretrieve
    except ImportError:
        from urllib import urlretrieve
    os.makedirs(dest_dir, exist_ok=True)
    urls = {
        "DejaVuSans.ttf": "https://github.com/dejavu-fonts/dejavu-fonts/raw/version_2_37/ttf/DejaVuSans.ttf",
        "DejaVuSans-Bold.ttf": "https://github.com/dejavu-fonts/dejavu-fonts/raw/version_2_37/ttf/DejaVuSans-Bold.ttf",
    }
    paths = []
    for name, url in urls.items():
        dest = os.path.join(dest_dir, name)
        print("Descargando", name, "...")
        urlretrieve(url, dest)
        paths.append(dest)
    return paths[0], paths[1]


def main():
    reg = bold = None
    for r, b in CANDIDATES:
        if os.path.isfile(r) and os.path.isfile(b):
            reg, bold = r, b
            print("Usando fuentes locales:")
            print(" ", r)
            print(" ", b)
            break
    if not reg:
        dest_dir = os.path.join(HERE, "static", "fonts")
        print("No hay TTF locales. Descargando a", dest_dir)
        try:
            reg, bold = download_fonts(dest_dir)
        except Exception as e:
            print("ERROR al descargar:", e)
            print("Descarga manualmente DejaVuSans.ttf y DejaVuSans-Bold.ttf")
            print("y colocalas en static/fonts/ o junto a app.py")
            sys.exit(1)

    with open(reg, "rb") as f:
        reg_b64 = base64.b64encode(zlib.compress(f.read(), 9)).decode("ascii")
    with open(bold, "rb") as f:
        bold_b64 = base64.b64encode(zlib.compress(f.read(), 9)).decode("ascii")

    with open(OUT, "w", encoding="ascii") as f:
        f.write("# Auto-generated by crear_fonts_data.py — no editar a mano\n")
        f.write("FONT_REGULAR_B64 = \"\"\"%s\"\"\"\n\n" % reg_b64)
        f.write("FONT_BOLD_B64 = \"\"\"%s\"\"\"\n" % bold_b64)

    print("OK ->", OUT)
    print("Tamano:", os.path.getsize(OUT), "bytes")
    print()
    print("Prueba:")
    print('  python -c "from fonts_data import FONT_REGULAR_B64; print(len(FONT_REGULAR_B64))"')


if __name__ == "__main__":
    main()
